version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 12
  reviewers:
  - mya-ake
  assignees:
  - mya-ake
  ignore:
  - dependency-name: "@types/aws-lambda"
    versions:
    - 8.10.71
    - 8.10.72
    - 8.10.73
    - 8.10.75
  - dependency-name: "@nuxtjs/tailwindcss"
    versions:
    - 3.4.2
    - 3.4.3
    - 4.0.1
    - 4.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: consola
    versions:
    - 2.15.0
    - 2.15.1
    - 2.15.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
