version: '3'

services:
  web:
    build: .
    container_name: deno-container
    image: deno-image
    environment:
      - MICRO_CMS_API_KEY
      - MICRO_CMS_API_ENDPOINT
    ports:
      - "8000:8000"
