service:
  name: ${self:custom.NAME}

frameworkVersion: ">=1.48.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  stage: ${self:custom.STAGE}

plugins:
  - deploy

custom:
  NAME: portfolio
  STAGE: ${file(./.configs/env.json):STAGE}
  AWS_SE_BUCKET_NAME: ${file(./.configs/env.json):AWS_SE_BUCKET_NAME}
  deploy:
    bucket: ${self:custom.AWS_SE_BUCKET_NAME}


package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - app/**
    - server/**
    - serverless-plugins/**
    - bin/**
    - scripts/**
    - LICENSE
    - README.md
    - package.json
    - yarn.lock
    - nodemon-dev.json
    - tsconfig.json
    - nuxt.config.ts
    - yarn-error.log
  include:
    - .lambda/**
    - .nuxt/**


functions:
  app:
    handler: .lambda/server/handler.appHandler
    timeout: 30
    memorySize: 128
    environment:
      NODE_ENV: production
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get

# resources:
#   Resources:
#     S3Bucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: ${self:custom.AWS_SE_BUCKET_NAME}
#         AccessControl: Private
#         PublicAccessBlockConfiguration:
#           BlockPublicAcls: True
#           BlockPublicPolicy: True
#           IgnorePublicAcls: True
#           RestrictPublicBuckets: True
#   Outputs:
#     S3BucketName:
#       Value: !Ref S3Bucket
