service:
  name: ${self:custom.NAME}

frameworkVersion: ">=1.48.0"

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  stage: ${self:custom.STAGE}

plugins:
  - deploy

custom:
  NAME: portfolio
  STAGE: ${file(./.configs/env.json):STAGE}
  AWS_S3_BUCKET_NAME: ${file(./.configs/env.json):AWS_S3_BUCKET_NAME}
  deploy:
    config: ${file(./.configs/deploy.config.json)}
    s3:
      name: ${self:custom.AWS_S3_BUCKET_NAME}
    cloudfront:
      comment: 'My portfolio'


package:
  excludeDevDependencies: true
  exclude:
    - .**
    - .**/*
    - app/**
    - server/**
    - serverless-plugins/**
    - bin/**
    - scripts/**
    - LICENSE
    - README.md
    - package.json
    - yarn.lock
    - nodemon-dev.json
    - tsconfig.json
    - nuxt.config.ts
    - yarn-error.log
  include:
    - .lambda/**
    - .nuxt/**


functions:
  app:
    handler: .lambda/server/handler.appHandler
    timeout: 30
    memorySize: 128
    environment:
      NODE_ENV: production
    events:
      - http:
          path: '/'
          method: get
      - http:
          path: '{proxy+}'
          method: get
