name: CI:PR

on:
  pull_request:
    branches:
      - master

jobs:
  basic_specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.23.3
      - name: Lint
        run: deno lint
      - name: Check format
        run: deno fmt --check
      - name: Check types
        run: deno check ./main.ts
      - name: Testing
        run: deno test
