name: CI:PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.3
      - name: Intall
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Check format
        run: yarn format:check
      - name: Unit Test
        run: yarn test:unit
      - name: Build
        env:
          APP_ENV: local
          USE_MOCK_SERVER: true
        run: yarn build
