name: CI:PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - name: Intall
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Check format
        run: yarn format:check
      - name: Build
        env:
          APP_ENV: local
          MICRO_CMS_ENDPOINT: ${{ secrets.MICRO_CMS_ENDPOINT }}
          MICRO_CMS_API_KEY: ${{ secrets.MICRO_CMS_API_KEY }}
        run: yarn build
