name: CI:PR

on:
  pull_request:
    branches:
      - master

jobs:
  basic_specs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.29.1
      - name: Lint
        run: deno lint
      - name: Check format
        run: deno fmt --check
      - name: Check types
        run: deno check ./main.ts
      - name: Testing
        run: deno test --allow-read
      # - name: Upload to Deno Deploy
      #   uses: denoland/deployctl@v1
      #   with:
      #     project: "mya-ake-portfolio"
      #     entrypoint: "./main.ts"
      #     import-map: "./import_map.json"
