name: CI:release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0
      - name: Mask
        env:
          API_ENDPOINT_PROD: ${{ secrets.API_ENDPOINT_PROD }}
          API_KEY_PROD: ${{ secrets.API_KEY_PROD }}
        run: |
          echo "::add-mask::$API_ENDPOINT_PROD"
          echo "::add-mask::$API_KEY_PROD"
      - name: Intall
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Check format
        run: yarn format:check
      - name: Deploy to production environment
        env:
          APP_ENV: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MICRO_CMS_ENDPOINT: ${{ secrets.MICRO_CMS_ENDPOINT }}
          MICRO_CMS_API_KEY: ${{ secrets.MICRO_CMS_API_KEY }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          API_ENDPOINT_PROD: ${{ secrets.API_ENDPOINT_PROD }}
          API_KEY_PROD: ${{ secrets.API_KEY_PROD }}
        run: yarn deploy
