name: Purge Cache

on:
  workflow_dispatch:
    inputs:
      paths:
        description: Enter the path to be purged."
        required: true
        type: string

jobs:
  purge_cache:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Purge Cache
        run: aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "${TARGET_PATHS}"
        env:
          TARGET_PATHS: ${{ inputs.paths }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
