name: Update Sitemap

on:
  schedule:
    - cron: 0 * * * *

jobs:
  update_sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.34.3
      - name: Fetch sitemap
        run: deno run --allow-net scripts/fetch_sitemap.ts
        